### ISSUE TITLE
npm run dev error: fetch API, autoprefixer, kleur, css-loader...

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#222]
### Environment

- Windows 10
![image](https://user-images.githubusercontent.com/17442457/85423084-3e764a80-b5b1-11ea-8d60-883f3750e6a2.png)

- Node and npm version
![image](https://user-images.githubusercontent.com/17442457/85423021-2c94a780-b5b1-11ea-98db-cb64d9062f59.png)

### npm install manually

- packages/backend
  - npm install
- packages/fronend
  - npm install
- /
  - npm install

### More actions

OF COURSE
- npm audit fix

### Error screenshots

- Mingw32
![image](https://user-images.githubusercontent.com/17442457/85423391-9ad96a00-b5b1-11ea-9701-ea18cc8d6d4b.png)

- Chrome
![image](https://user-images.githubusercontent.com/17442457/85423451-adec3a00-b5b1-11ea-9b87-c811e5d99642.png)

- Chrome all console texts
```
content.js:4 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:4
content.js:5 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:5
content.js:5 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:5
log.js:21 [HMR] Waiting for update signal from WDS...
index.js:1749 Fetch API cannot load file:///C:/Users/kjp10/OneDrive/Documents/GitHub/nyangterest/packages/frontend/node_modules/autoprefixer/lib/autoprefixer.js. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ index.js:1749
index.js:1749 Fetch API cannot load file:///C:/Users/kjp10/OneDrive/Documents/GitHub/nyangterest/packages/frontend/node_modules/postcss-preset-env/index.js. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ index.js:1749
index.js:152 Uncaught Error: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Package exports for 'C:\Users\kjp10\OneDrive\Documents\GitHub\nyangterest\packages\frontend\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\kjp10\OneDrive\Documents\GitHub\nyangterest\packages\frontend\node_modules\autoprefixer\lib\autoprefixer.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\kjp10\OneDrive\Documents\GitHub\nyangterest\packages\frontend\node_modules\postcss-preset-env\index.js:5:36)
    at Object../node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/reset-css/reset.css (http://localhost:3000/static/js/0.chunk.js:23347:7)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:787:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Object../node_modules/reset-css/reset.css (http://localhost:3000/static/js/0.chunk.js:108515:15)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:787:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Module../src/Components/GlobalStyles.js (http://localhost:3000/static/js/main.chunk.js:387:67)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:787:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Module../src/Components/App.js (http://localhost:3000/static/js/main.chunk.js:191:71)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:787:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Module../src/index.js (http://localhost:3000/static/js/main.chunk.js:5918:73)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:787:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Object.1 (http://localhost:3000/static/js/main.chunk.js:6114:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:787:30)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19)
    at http://localhost:3000/static/js/main.chunk.js:1:57
:3000/internal/modules/cjs/loader.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/internal/modules/cjs/helpers.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:1437 ./src/fonts/fonts.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/fonts/fonts.css)
Error: Package exports for 'C:\Users\kjp10\OneDrive\Documents\GitHub\nyangterest\packages\frontend\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
console.<computed> @ index.js:1437
index.js:1437 ./node_modules/reset-css/reset.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/reset-css/reset.css)
Error: Package exports for 'C:\Users\kjp10\OneDrive\Documents\GitHub\nyangterest\packages\frontend\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
console.<computed> @ index.js:1437
index.js:1437 ./src/layer_common.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/layer_common.css)
Error: Package exports for 'C:\Users\kjp10\OneDrive\Documents\GitHub\nyangterest\packages\frontend\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
```

**Comment by yoonucho** [comment]
@jongfeel  헉 뭐가 문제일까요 지금은 시간이 늦어서 내일 살펴보겠습니다. ㅠㅠ

**Comment by jongfeel** [comment]
@yoonucho 

뭐 당장 안하셔도 되고 계획 세우셔서 보고 천천히 알려주세요.

개발환경 세팅할 떄 추가로 뭔가 더 해줘야 하는게 있는데 제 노트북에는 없는 게 있는 거 같습니다.

**Comment by yoonucho** [comment]
@jongfeel 

멘토님의 에러도 이 원인인지는 모르겠으나. 제가 시도한 방법은 다음과 같습니다.

1. npm install로 설치 (root, frontend,backend)
2. 추가로 yarn install로 설치 (root, frontend,backend)
3. frontend폴더(\packages\frontend)에서 기존의 styled-components를 명령어로 제거 
<pre>yarn remove styled-components</pre>
4. styled-components 버전 4.2.0으로 재설치
<pre>yarn add styled-components@4.2.0</pre>
5. 서버 재실행
 

저도 냥터레스트를 클론하여서 설치를 시도하였습니다.
npm install로만 진행을 했더니 아래와 같이 브라우저상에선 로컬서버가 실행도 되지 않았습니다.

![주석 2020-06-24 144335](https://user-images.githubusercontent.com/2981954/85516477-34982a00-b639-11ea-8330-30ee7929bc60.jpg)

프론트경로 터미널창에서는 아래와 같은 에러가 나왔습니다.
![주석 2020-06-24 164039](https://user-images.githubusercontent.com/2981954/85516850-9f496580-b639-11ea-9a87-59131c47e085.jpg)

제 기존의 폴더와 비교를 해보는데 제 기존 폴더에도 yarn.lock파일이 없고 클론한 폴더에도 yarn.lock파일이 없었습니다.
그리고 생각이 든게 저희는 npm과 yarn을 병행해서 사용하고 있는데 얼마전에 .gitignore에 lock파일을  등록하여서
기존에 yarn패키지가 설치된 기존 폴더는 문제가 없던거 같고 그 이후 새로운 프로젝트는 yarn 정보가 없으니 문제가 생긴거 같습니다.
그래서 yarn install를 추가로 설치를 하였습니다.
그랬더니 아래와 같은 브라우저상 에러가 나왔습니다.

![주석 2020-06-24 145306](https://user-images.githubusercontent.com/2981954/85517910-b177d380-b63a-11ea-99db-bbc553520ca3.jpg)

확인해보니 styled-components에러라서 충돌이 있는듯하여 지웠었고 재설치를 하였습니다.

그런데 재설치를 하면서 버전업이 되니 렌더링이 조금 달리 보이는 이슈가 생겼습니다.

삭제 후 기존 버전인 4.2.0으로 재설치를 하니 문제가 해결되었습니다.

한번 제가 한 방법을 시도해보심이 어떨까요 멘토님 개발환경 에러도 css 관련 모듈에러라 이게 원인일거라는 생각이 듭니다.

**Comment by jongfeel** [comment]
우선 저는 windows 환경이므로 [여기](https://classic.yarnpkg.com/en/docs/install/#windows-stable)에서 yarn을 설치한 후에

```
$ yarn install
$ cd packages/frontend
$ yarn install
```

이렇게 진행했습니다.

거의 10분 정도 걸린거 같은데 패키지 설치가 진행되었고
실행이 잘 됐습니다.

![image](https://user-images.githubusercontent.com/17442457/85522601-d3745480-b640-11ea-9bba-9ddb5424c231.png)

### To do

yarn tool에 dependency가 있다는 걸 설치 매뉴얼 문서에 추가 해야 할 것 같습니다.

**Comment by yoonucho** [comment]
@jongfeel 

오호! yarn install 만으로도 해결이 되셨군요! 다행입니다.
네 설치 매뉴얼 문서에 변경을 해야겠습니다. 그러면  .gitignore에 넣은 .lock파일들은 지우지 않아도 될까요?

**Comment by jongfeel** [comment]
설치 매뉴얼대로 해서 문제 없다면, 상관 없을 것 같습니다.
